---
- name: Create Azure resources
  hosts: localhost
  connection: local
  gather_facts: false

  module_defaults:
    group/azure:
      location: eastus

  tasks:
    #  Check for controller job template _SANDBOX_ID var or terminal env var
    - name: Check if this is Instruqt environment
      ansible.builtin.set_fact:
        __sandbox_id: "{{ _SANDBOX_ID | default(lookup('ansible.builtin.env', '_SANDBOX_ID')) }}"

    - name: Copy Instruqt lab SSH keys to demo folder
      when: __sandbox_id | length > 0
      block:
        # Evaluates to true if running from the terminal
        - name: Check if ~/.ssh/instruqt_lab exists
          ansible.builtin.stat:
            path: ~/.ssh/instruqt_lab
          register: __instruqt_ssh_key

        - name: Create files folder
          ansible.builtin.file:
            path: files
            state: directory
            mode: "0755"
          when: __instruqt_ssh_key.stat.exists

        - name: Copy Instruqt lab SSH keys
          ansible.builtin.copy:
            src: ~/.ssh/{{ item.name }}
            dest: files/azure_demo_ssh_key{{ item.name | splitext | last }}
            mode: "{{ item.mode }}"
          loop:
            - name: instruqt_lab
              mode: "0600"
            - name: instruqt_lab.pub
              mode: "0644"
          when: __instruqt_ssh_key.stat.exists

    - name: Generate local SSH keys if not Instruqt environment
      when: __sandbox_id | length == 0
      block:
        - name: Create files folder
          ansible.builtin.file:
            path: files
            state: directory
            mode: "0755"

        - name: Generate Linux SSH key called files/azure_demo_ssh_key # noqa name[template]
          community.crypto.openssh_keypair:
            path: files/azure_demo_ssh_key
            type: rsa
            size: 4096
            state: present
            force: false
          register: azure_key

    - name: Create resource group called rg-lightspeed
      azure.azcollection.azure_rm_resourcegroup:
        name: rg-lightspeed
        location: eastus
      register: rg

    - name: Create virtual network called vnet-lightspeed
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: rg-lightspeed
        name: vnet-lightspeed
        address_prefixes: 10.0.0.0/16

    - name: Add subnet called subnet-lightspeed
      azure.azcollection.azure_rm_subnet:
        resource_group: rg-lightspeed
        name: subnet-lightspeed
        address_prefix: 10.0.1.0/24
        virtual_network: vnet-lightspeed

    - name: Create public IP address called ip-lightspeed
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: rg-lightspeed
        allocation_method: Static
        name: ip-lightspeed
      register: ip_lightspeed

    - name: Create azure_public_ip var
      ansible.builtin.set_fact:
        azure_public_ip: "{{ ip_lightspeed.state.ip_address }}"

    - name: Create Network Security Group that allows SSH
      azure.azcollection.azure_rm_securitygroup:
        resource_group: rg-lightspeed
        name: secgroup-lightspeed
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create virtual network interface
      azure.azcollection.azure_rm_networkinterface:
        resource_group: rg-lightspeed
        name: nic-lightspeed
        virtual_network: vnet-lightspeed
        subnet: subnet-lightspeed
        public_ip_name: ip-lightspeed
        security_group: secgroup-lightspeed
