---
- name: EC2 Cloud Operations
  hosts: localhost
  connection: local
  gather_facts: false

  module_defaults:
    group/aws:
      region: us-east-1

  vars:
    ec2_instance:
      name: lightspeed-instance-01
      key_name: lightspeed-keypair
      image_id: ami-016eb5d644c333ccb # RHEL 9 us-east-1
      tags:
        function: lightspeed-demo
      security_group: secgroup-lightspeed

  tasks:
    - name: Gather subnet info tag:Name subnet-lightspeed
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          tag:Name: subnet-lightspeed
      register: subnet_info

    - name: Create vpc_subnet_id var
      ansible.builtin.set_fact:
        vpc_subnet_id: "{{ subnet_info.subnets[0].subnet_id }}"

    - name: Provision t3.micro instance using ec2_instance var
      amazon.aws.ec2_instance:
        state: running
        name: "{{ ec2_instance.name }}"
        key_name: "{{ ec2_instance.key_name }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        instance_type: t3.micro
        security_group: "{{ ec2_instance.security_group }}"
        network:
          assign_public_ip: true
        image_id: "{{ ec2_instance.image_id }}"
        tags: "{{ ec2_instance.tags }}"
      register: ec2
